### ISSUE TITLE
wax.struct的结构对象是否存在内存泄露？

### ISSUE THREAD

**Issue by dourgulf** [piaojin/iOS-WaxPatch#2]
我写了一个测试代码，lua是这样的
wax.struct.create("myrect", "dd", "w", "h")
function test()
	local r = myrect(1,3)
	print(r[2])
	print(r.w)
	r=nil
end
test()
调试的时候，断点在wax_struct.m的__gc里，发现并没有执行到这里，不知道这样算不算有内存泄露了。
看代码的分析过程，在创建对象（也就是执行createClosure的时候），分配了user data的，应该要在某个时候释放的吧？

**Comment by dourgulf** [comment]
没有问题，只是我对GC理解上不够深入，lua不是实时释放的，GC对象在内存累计到一定程度才会触发。

**Comment by piaojin** [comment]
不好意思,这个就没去研究过了,不清楚,有一大段时间没去碰wax了.
